*** Variables ***
${INPUT_PRODUCT_QUANTITY}    //input[@id="input0"]
${SELLING_PRICE}             //div[@class="product-detail-summary"]//div[@class="selling-price"]
${ฺBUTTON_ADD_TO_CART}        //button[contains(@class, 'btn-add-to-cart') and contains(text(), "หยิบใส่ตะกร้า")]
${MODAL_TITLE}               //div[@class="modal-title"]//div[@class="left"]
${MODAL_CLOSE}               //div[@class="modal-title"]//div[@class="right"]